name: Проверка датапака на ошибки при PR

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Установка дополнительных пакетов
        run: sudo apt-get install -y python3-pip && sudo pip install hjson

      - name: Проверка на ошибки
        run: scripts/lint.sh
